WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/home/liang/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py:563: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Total of - 13729 - Trainable Parameters
Epoch Loop:   0%|                                                                                              | 0/200 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/liang/文档/Coding/Machine Learning/MetaAF/zoo/eq/eq.py", line 301, in <module>
    outer_learned, losses = system.train(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 391, in train
    self.outer_learnable, aux = self.epoch_loop(meta_opt_s, key)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 412, in epoch_loop
    train_loop_losses, meta_opt_s = self.train_loop(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 543, in train_loop
    train_step_losses, aux = self.train_step(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 605, in train_step
    train_step_losses, aux = self.outer_loop(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/_src/api.py", line 2013, in cache_miss
    out_tree, out_flat = f_pmapped_(*args, **kwargs)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/_src/api.py", line 1889, in pmap_f
    out = pxla.xla_pmap(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/core.py", line 1863, in bind
    return map_bind(self, fun, *args, **params)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/core.py", line 1895, in map_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/core.py", line 1866, in process
    return trace.process_map(self, fun, tracers, params)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/core.py", line 660, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 801, in xla_pmap_impl
    compiled_fun, fingerprint = parallel_callable(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/linear_util.py", line 285, in memoized_fun
    ans = call(fun, *args)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 832, in parallel_callable
    pmap_executable = pmap_computation.compile()
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1097, in compile
    self._executable = PmapExecutable.from_hlo(self._hlo, **self.compile_args)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1122, in from_hlo
    raise ValueError(msg.format(shards.num_global_shards,
jax._src.traceback_util.UnfilteredStackTrace: ValueError: compiling computation that requires 2 logical devices, but only 1 XLA devices are available (num_replicas=2, num_partitions=1)
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/liang/文档/Coding/Machine Learning/MetaAF/zoo/eq/eq.py", line 301, in <module>
    outer_learned, losses = system.train(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 391, in train
    self.outer_learnable, aux = self.epoch_loop(meta_opt_s, key)
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 412, in epoch_loop
    train_loop_losses, meta_opt_s = self.train_loop(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 543, in train_loop
    train_step_losses, aux = self.train_step(
  File "/home/liang/miniconda3/lib/python3.9/site-packages/metaaf/meta.py", line 605, in train_step
    train_step_losses, aux = self.outer_loop(
ValueError: compiling computation that requires 2 logical devices, but only 1 XLA devices are available (num_replicas=2, num_partitions=1)